### ISSUE TITLE
No edit box in BP-Nouveau for admins under the Announcements tab

### ISSUE THREAD

**Issue by rgilman** [cuny-academic-commons/bp-group-announcements#8]
Here's what I get:

![screen shot 2018-12-17 at 4 31 04 pm](https://user-images.githubusercontent.com/615052/50124381-45ccd300-0219-11e9-8523-63d05827b4bb.png)

That long narrow box is where the edit box should be. Works fine in BP-Legacy.

**Comment by boonebgorges** [comment]
Hi @rgilman - The PR in #9 mostly fixes this. Posting an item still doesn't dynamically update the stream (but it does show a success message) so I think it's good enough. Some deep wizardry is necessary to make it happen because of a lack of appropriate filters in Nouveau, and the ancient nature of the current plugin.

Are you able to give it a test?

**Comment by rgilman** [comment]
@boonebgorges, it works for me as you describe and I agree that the lack of dynamic updating is still good enough. 

The announcement shows within the activity stream of the appropriate group. However, when using the dropdown filter on Groups > Activity, the announcement shows for "updates" but not "group updates." Hardly a deal breaker but a bit confusing.

Thanks for all your deep wizardry here and in so many other WP-related places.

**Comment by boonebgorges** [comment]
Thanks for confirming, @rgilman !
